name: dongnerang
description: dongnerang flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.8.1
  logger: ^1.1.0
  flutter_switch: ^0.3.2
  carousel_slider: ^4.1.1
  #  firebase
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.1.0

  # URL
  url_launcher: ^6.1.4
  webview_flutter: ^2.0.4
  get: ^4.6.5
  http: ^0.13.4
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.5
  flutter_signin_button: ^2.0.0
  flutter_html: ^2.2.1
  flutter_colorpicker: ^1.0.3
  google_sign_in: ^5.3.3
  permission_handler: ^10.0.0
  kakao_flutter_sdk: ^1.2.2
  kakao_flutter_sdk_share: ^1.2.1
  cupertino_icons: ^1.0.2
  filter_list: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_keyboard_visibility: ^5.3.0
  mask_text_input_formatter: ^2.3.0
  cached_network_image: ^3.2.1
  material_tag_editor: ^0.1.2
  fluttertagselector: ^0.1.0
  intl: ^0.17.0
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
  flutter_slidable: ^2.0.0
  lottie: ^1.4.3
  flutter_native_splash: ^2.0.5
  # flutter messaging fnc
  firebase_messaging: ^14.0.4
  flutter_local_notifications: ^9.6.0
  fluttertoast: ^8.1.1
  google_mobile_ads: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

