name: dongnerang
description: dongnerang flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.2+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #  firebase
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.0.4
  # Kakao
  kakao_flutter_sdk: ^1.3.0-beta.4 # 전체 추가
  kakao_flutter_sdk_share: ^1.3.0-beta.4 # 카카오톡 공유
  # Google map
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  # Hive local db
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # URL
  url_launcher: ^6.1.4
  webview_flutter: ^2.0.4
  get: ^4.6.5
  http: ^0.13.4
  store_redirect: ^2.0.1
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master
  firebase_dynamic_links: ^5.0.11
  # Util
  flutter_cupertino_localizations: ^1.0.1
  latlong2: ^0.8.1
  logger: ^1.1.0
  flutter_switch: ^0.3.2
  carousel_slider: ^4.1.1
  flutter_easyloading: ^3.0.5
  flutter_signin_button: ^2.0.0
  flutter_html: ^2.2.1
  flutter_colorpicker: ^1.0.3
  permission_handler: ^10.0.0
  crypto: ^3.0.2
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^4.2.0
  cupertino_icons: ^1.0.5
  filter_list: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_keyboard_visibility: ^5.3.0
  mask_text_input_formatter: ^2.3.0
  cached_network_image: ^3.2.1
  material_tag_editor: ^0.1.2
  fluttertagselector: ^0.1.0
  flutter_slidable: ^2.0.0
  dropdown_button2: ^1.9.2
  lottie: ^1.4.3
  flutter_native_splash: ^2.0.5
  flutter_local_notifications: ^9.6.0
  fluttertoast: ^8.1.1
  google_mobile_ads: ^2.2.0
  dots_indicator: ^2.1.0
  app_tracking_transparency: ^2.0.3
  pull_to_refresh: ^2.0.0
  new_version: ^0.3.1
  auto_size_text: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_downloader: ^1.10.2
  path_provider: ^2.0.12
  infinite_scroll_pagination: ^3.2.0


dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # Hive local db
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/mypage/

